languageCode = "en"
languageName = "English"
weight = 1
title = "Matt's Musings"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Matt's Personal Website"
  copyright = "Copy, _right?_ 🤔"

